batch_size: 256
capacity: 100000
env_name: LunarLander-v2
eps_end: 0.15
eps_last_episode: 100
eps_start: 1.0
gamma: 0.5654915035000824
hidden_size: 128
loss_fn: !!python/name:torch.nn.functional.smooth_l1_loss ''
lr: 0.012418913928692698
optim: !!python/name:torch.optim.adamw.AdamW ''
policy: !!python/name:__main__.epsilon_greedy ''
samples_per_epoch: 10000
sync_rate: 10
