a_end: 0.0
a_last_episode: 100
a_start: 0.5
b_end: 1
b_last_episode: 100
b_start: 0.4
batch_size: 256
capacity: 10000
env_name: FlappyBird-v0
eps_end: 0.01
eps_last_episode: 1000
eps_start: 1.0
gamma: 0.9
hidden_size: 512
loss_fn: !!python/name:torch.nn.functional.smooth_l1_loss ''
lr: 0.0005
optim: !!python/name:torch.optim.adamw.AdamW ''
policy: !!python/name:__main__.epsilon_greedy ''
samples_per_epoch: 10000
sync_rate: 10
